### ISSUE TITLE
Sign MacOS binaries

### ISSUE THREAD

**Issue by mauromorales** [mudler/LocalAI#2390]
**Is your feature request related to a problem? Please describe.**

When trying to run on MacOS, you need to give the binary permision via Gatekeeper which can get annoying see: https://github.com/mudler/LocalAI/pull/2389

**Describe the solution you'd like**

You can sign the binaries so all that the user needs to do is to accept in a pop up when running for the first time, which is a lot more user friendly. See https://developer.apple.com/developer-id/

**Describe alternatives you've considered**

Keep allowing in Gatekeepr

**Additional context**

**Comment by dave-gray101** [comment]
Hey @mauromorales !

I agree that the gatekeeper stuff gets annoying. That's why a while ago I added the `osx-signed` make target.

This will let you self-sign a binary that OSX won't complain about.

I currently don't have an Apple Developer Program membership to generate public signatures, so until that changes, someone else on the team gets one, or someone corrects me that I'm wrong about needing it at all, I think self-signing will be the way to go!

**Comment by mauromorales** [comment]
@dave-gray101 makes sense, it's not a huge problem but more like a paper cut. I'm also checking if I can create a brew formula to avoid this altogether.

**Comment by mauromorales** [comment]
Opened a PR for the brew formula, might need some tuning because I'm not passing any special flags plus eventually, it might be nice to also add a service or such, but at least I can install and configure using env vars

**Comment by qdrddr** [comment]
Having this app on mac via `brew` would be great. Makes life much easier

**Comment by mauromorales** [comment]
It took a bit but LocalAI formula has been merged https://formulae.brew.sh/formula/localai

Please test it out and help to improve it.

I will close this issue since IMO the brew solution is good enough
