### ISSUE TITLE
Proposal: Move docs (back?) to its own repo

### ISSUE THREAD

**Issue by dave-gray101** [mudler/LocalAI#4011]
Part of the CI Speedup Project https://github.com/users/dave-gray101/projects/2/views/1

In order to simplify when we run the pipelines required steps, I propose we move the localai.io netlify site out of the main repo and into its own.

I know that for a while we **used to do this and we stopped**. I don't remember why we stopped. Hopefully somebody else can tell me why this is or is not a good idea

If we do this, we'll need to fix up some scripts to pull the version numbers etc from the main repo

**Comment by mudler** [comment]
> Part of the CI Speedup Project https://github.com/users/dave-gray101/projects/2/views/1
> 
> In order to simplify when we run the pipelines required steps, I propose we move the localai.io netlify site out of the main repo and into its own.

mmhmhmhmh. I'm a bit reluctant to do that and move things out again, not because of the complexity involved, but for the primarly reason of why we did that in the first place (below).

> 
> I know that for a while we **used to do this and we stopped**. I don't remember why we stopped. Hopefully somebody else can tell me why this is or is not a good idea

One of the main point that was the motivation to go back at the monolithic approach is that it is much easier to keep the docs consistent and aligned with the code. When having it outside it made it was really hard to keep in track with code changes, and usually docs were completely neglected.

**Comment by dave-gray101** [comment]
Honestly that's a pretty compelling reason to keep them together.

I'll dig around the github docs some more and try find a way to get docs only changes to bypass CI - this was mostly to make that process easier.
